Added guide for auto updating node with docker
thepower/power-docs pull request #11
Opened 2022-11-10 23:52 UTC by ArthurPatriot

2022-11-11 08:47 UTC, EZabotkin requested changes
Need some minor changes

2022-11-11 08:47 UTC, EZabotkin commented on docs/Community/phase-1/02-download-build-run-docker.md
> +- [Step 6 (optional): Automate updates for node with Watchtower](#step-6-optional-automate-updates-for-node-with-watchtower)
Step 6 (optional): Automated updates for node with Watchtower

2022-11-11 08:47 UTC, EZabotkin commented on docs/Community/phase-1/02-download-build-run-docker.md
> +Every 24 hours, the [Watchtower](https://containrrr.dev/watchtower/) will check whether there is a new version of The Power Node and will update if so.
Every 24 hours, the [Watchtower](https://containrrr.dev/watchtower/) will check if a new version of The Power Node is available and update it if so.

2022-11-11 08:47 UTC, EZabotkin commented on docs/Community/phase-1/02-download-build-run-docker.md
> +
Add a 3rd level subheader:

### Start a container

2022-11-16 12:39 UTC, giDai7ja approved these changes
@EZabotkin
Useful information
See that it fits well into the main documentation

2022-11-17 07:05 UTC, giDai7ja approved these changes

2022-11-17 07:49 UTC, EZabotkin approved these changes

2022-11-17 07:53 UTC, merged